export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const POST_ORGANIZATION_SUCCESS = "POST_ORGANIZATION_SUCCESS";
export const POST_ORGANIZATION_FAILED = "POST_ORGANIZATION_FAILED";

export const PUT_ORGANIZATION_SUCCESS = "PUT_ORGANIZATION_SUCCESS";
export const PUT_ORGANIZATION_FAILED = "PUT_ORGANIZATION_FAILED";

export const GET_ORGANIZATIONS_SUCCESS = "GET_ORGANIZATIONS_SUCCESS";
export const GET_ORGANIZATIONS_FAILED = "GET_ORGANIZATIONS_FAILED";

export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";

export const SET_EDIT_ID = "SET_EDIT_ID";

export const DATA_LOADED = "DATA_LOADED";

export const POST_LEAVE_ORGANIZATION_SUCCESS =
  "POST_LEAVE_ORGANIZATION_SUCCESS";
