export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const POST_ORGANIZATION_SUCCESS = "POST_ORGANIZATION_SUCCESS";
export const POST_ORGANIZATION_FAILED = "POST_ORGANIZATION_FAILED";

export const GET_ORGANIZATIONS_SUCCESS = "GET_ORGANIZATIONS_SUCCESS";
export const GET_ORGANIZATIONS_FAILED = "GET_ORGANIZATIONS_FAILED";

export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
